### PR TITLE
Add publish task to build wheel

### PR DESCRIPTION
**Pull request by marcelotduarte**

### CODE REVIEW

**Comment by anthony-tuininga** [comment]
I'll leave this one to the side for now. I'd rather just have the builds done and do the upload manually for at least one release so I can make sure everything is working properly. Once released no changes are allowed!

**Comment by marcelotduarte** [comment]
I use this at last for a year in cx_Freeze. I copied from it. It works!

The secret used in ${{ secrets.pypi_password }} needs to be created on the settings page of your project on GitHub. See [Creating & using secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

**Comment by marcelotduarte** [comment]
I tested this PR and PR #14 and worked.
https://github.com/marcelotduarte/cx_Logging/actions/runs/3453502665

**Comment by anthony-tuininga** [comment]
I'm not worried about this PR working -- although I'm glad to hear that it does! I'm more worried that the build process might be flawed and then publish artifacts that are incorrect. So I'll wait until at least one build run has been successful before implementing this. Thanks for it, though!

**Comment by marcelotduarte** [comment]
You can download the artifacts in my link to check ;-)

**Comment by marcelotduarte** [comment]
Alias, I use the trick in: https://github.com/marcelotduarte/cx_Logging/commit/dd5c3517f60a439ade24498f7018b65659aeb3b3
To build manually. I can send this PR.

**Comment by marcelotduarte** [comment]
Hi Anthony!
I updated this PR to publish the wheels using https://github.com/pypa/gh-action-pypi-publish#trusted-publishing
It is complementary to PR #16 
With these two PRs, we can support Python 3.12 and publish it to Pypi.

**Comment by anthony-tuininga** [comment]
I merged the other MR. Can you fix the conflicts with this one?

**Comment by marcelotduarte** [comment]
Fixed!

**Comment by anthony-tuininga** [comment]
Merged. Thanks, Marcelo!

**Pull request merged**
