### PR TITLE
Build wheels and sdist for Python 3.8-3.12

### PR DESCRIPTION
**Pull request by marcelotduarte**

### CODE REVIEW

**Comment by anthony-tuininga** [comment]
Thanks, Marcelo!

**Comment by marcelotduarte** [comment]
@anthony-tuininga Can you release a version supporting Python 3.12 soon?

**Comment by anthony-tuininga** [comment]
I have pushed some small changes to eliminate some deprecation warnings and modernize the Python code. Take a look and let me know if you that works for you. If so, I'll go ahead and release 3.2.

**Comment by marcelotduarte** [comment]
I tested it with cx_Freeze using the service sample in py 3.10 and 3.12 and it works!

**Pull request merged**
